version: "3"

env:
  DEFAULT_BRANCH:
    sh: git remote show origin | grep 'HEAD branch' | awk '{print $NF}'

tasks:
  gd:
    silent: true
    cmds:
      - git fetch --prune
      - git branch | grep -v $DEFAULT_BRANCH | grep -v "^\*.*" | xargs git branch -D
