version: "3"

env:
  DEFAULT_BRANCH:
    sh: git remote show origin | grep 'HEAD branch' | awk '{print $NF}'

tasks:
  gd:
    cmds:
      - git fetch --prune
      - echo "Default branch is $DEFAULT_BRANCH"
      - git branch | grep -v $DEFAULT_BRANCH | xargs git branch -D
